#include <dtc.hpp>

dtc_description obd_table[] =
    {
        {.code = 0x0001, .description = "Fuel Volume Regulator Control Circuit/Open"},
        {.code = 0x0002, .description = "Fuel Volume Regulator Control Circuit Range/Performance"},
        {.code = 0x0003, .description = "Fuel Volume Regulator Control Circuit Low"},
        {.code = 0x0004, .description = "Fuel Volume Regulator Control Circuit High"},
        {.code = 0x0005, .description = "Fuel Shutoff Valve A Control Circuit/Open"},
        {.code = 0x0006, .description = "Fuel Shutoff Valve A Control Circuit Low"},
        {.code = 0x0007, .description = "Fuel Shutoff Valve A Control Circuit High"},
        {.code = 0x0008, .description = "Engine Position System Performance"},
        {.code = 0x0009, .description = "Engine Position System Performance"},
        {.code = 0x0010, .description = "A Camshaft Position Actuator Circuit"},
        {.code = 0x0011, .description = "A Camshaft Position : Timing Over-Advanced or System Performance"},
        {.code = 0x0012, .description = "A Camshaft Position : Timing Over-Retarded"},
        {.code = 0x0013, .description = "B Camshaft Position : Actuator Circuit"},
        {.code = 0x0014, .description = "B Camshaft Position : Timing Over-Advanced or System Performance"},
        {.code = 0x0015, .description = "B Camshaft Position : Timing Over-Retarded"},
        {.code = 0x0016, .description = "Crankshaft Position : Camshaft Position Correlation"},
        {.code = 0x0017, .description = "Crankshaft Position : Camshaft Position Correlation"},
        {.code = 0x0018, .description = "Crankshaft Position : Camshaft Position Correlation"},
        {.code = 0x0019, .description = "Crankshaft Position : Camshaft Position Correlation"},
        {.code = 0x0020, .description = "A Camshaft Position Actuator Circuit"},
        {.code = 0x0021, .description = "A Camshaft Position : Timing Over-Advanced or System Performance"},
        {.code = 0x0022, .description = "A Camshaft Position : Timing Over-Retarded"},
        {.code = 0x0023, .description = "B Camshaft Position : Actuator Circuit"},
        {.code = 0x0024, .description = "B Camshaft Position : Timing Over-Advanced or System Performance"},
        {.code = 0x0025, .description = "B Camshaft Position : Timing Over-Retarded"},
        {.code = 0x0026, .description = "Intake Valve Control Solenoid Circuit Range/Performance"},
        {.code = 0x0027, .description = "Exhaust Valve Control Solenoid Circuit Range/Performance"},
        {.code = 0x0028, .description = "Intake Valve Control Solenoid Circuit Range/Performance"},
        {.code = 0x0029, .description = "Exhaust Valve Control Solenoid Circuit Range/Performance"},
        {.code = 0x0030, .description = "HO2S Heater Control Circuit"},
        {.code = 0x0031, .description = "HO2S Heater Control Circuit Low"},
        {.code = 0x0032, .description = "HO2S Heater Control Circuit High"},
        {.code = 0x0033, .description = "Turbo Charger Bypass Valve Control Circuit"},
        {.code = 0x0034, .description = "Turbo Charger Bypass Valve Control Circuit Low"},
        {.code = 0x0035, .description = "Turbo Charger Bypass Valve Control Circuit High"},
        {.code = 0x0036, .description = "HO2S Heater Control Circuit"},
        {.code = 0x0037, .description = "HO2S Heater Control Circuit Low"},
        {.code = 0x0038, .description = "HO2S Heater Control Circuit High"},
        {.code = 0x0039, .description = "Turbo/Super Charger Bypass Valve Control Circuit Range/Performance"},
        {.code = 0x0040, .description = "O2 Sensor Signals Swapped Bank 1 Sensor 1/ Bank 2 Sensor 1"},
        {.code = 0x0041, .description = "O2 Sensor Signals Swapped Bank 1 Sensor 2/ Bank 2 Sensor 2"},
        {.code = 0x0042, .description = "HO2S Heater Control Circuit"},
        {.code = 0x0043, .description = "HO2S Heater Control Circuit Low"},
        {.code = 0x0044, .description = "HO2S Heater Control Circuit High"},
        {.code = 0x0045, .description = "Turbo/Super Charger Boost Control Solenoid Circuit/Open"},
        {.code = 0x0046, .description = "Turbo/Super Charger Boost Control Solenoid Circuit Range/Performance"},
        {.code = 0x0047, .description = "Turbo/Super Charger Boost Control Solenoid Circuit Low"},
        {.code = 0x0048, .description = "Turbo/Super Charger Boost Control Solenoid Circuit High"},
        {.code = 0x0049, .description = "Turbo/Super Charger Turbine Overspeed"},
        {.code = 0x0050, .description = "HO2S Heater Control Circuit"},
        {.code = 0x0051, .description = "HO2S Heater Control Circuit Low"},
        {.code = 0x0052, .description = "HO2S Heater Control Circuit High"},
        {.code = 0x0053, .description = "HO2S Heater Resistance"},
        {.code = 0x0054, .description = "HO2S Heater Resistance"},
        {.code = 0x0055, .description = "HO2S Heater Resistance"},
        {.code = 0x0056, .description = "HO2S Heater Control Circuit"},
        {.code = 0x0057, .description = "HO2S Heater Control Circuit Low"},
        {.code = 0x0058, .description = "HO2S Heater Control Circuit High"},
        {.code = 0x0059, .description = "HO2S Heater Resistance"},
        {.code = 0x0060, .description = "HO2S Heater Resistance"},
        {.code = 0x0061, .description = "HO2S Heater Resistance"},
        {.code = 0x0062, .description = "HO2S Heater Control Circuit"},
        {.code = 0x0063, .description = "HO2S Heater Control Circuit Low"},
        {.code = 0x0064, .description = "HO2S Heater Control Circuit High"},
        {.code = 0x0065, .description = "Air Assisted Injector Control Range/Performance"},
        {.code = 0x0066, .description = "Air Assisted Injector Control Circuit or Circuit Low"},
        {.code = 0x0067, .description = "Air Assisted Injector Control Circuit High"},
        {.code = 0x0068, .description = "MAP/MAF - Throttle Position Correlation"},
        {.code = 0x0069, .description = "Manifold Absolute Pressure - Barometric Pressure Correlation"},
        {.code = 0x0070, .description = "Ambient Air Temperature Sensor Circuit"},
        {.code = 0x0071, .description = "Ambient Air Temperature Sensor Range/Performance"},
        {.code = 0x0072, .description = "Ambient Air Temperature Sensor Circuit Low"},
        {.code = 0x0073, .description = "Ambient Air Temperature Sensor Circuit High"},
        {.code = 0x0074, .description = "Ambient Air Temperature Sensor Circuit Intermittent"},
        {.code = 0x0075, .description = "Intake Valve Control Solenoid Circuit"},
        {.code = 0x0076, .description = "Intake Valve Control Solenoid Circuit Low"},
        {.code = 0x0077, .description = "Intake Valve Control Solenoid Circuit High"},
        {.code = 0x0078, .description = "Exhaust Valve Control Solenoid Circuit"},
        {.code = 0x0079, .description = "Exhaust Valve Control Solenoid Circuit Low"},
        {.code = 0x0080, .description = "Exhaust Valve Control Solenoid Circuit High"},
        {.code = 0x0081, .description = "Intake Valve Control Solenoid Circuit"},
        {.code = 0x0082, .description = "Intake Valve Control Solenoid Circuit Low"},
        {.code = 0x0083, .description = "Intake Valve Control Solenoid Circuit High"},
        {.code = 0x0084, .description = "Exhaust Valve Control Solenoid Circuit"},
        {.code = 0x0085, .description = "Exhaust Valve Control Solenoid Circuit Low"},
        {.code = 0x0086, .description = "Exhaust Valve Control Solenoid Circuit High"},
        {.code = 0x0087, .description = "Fuel Rail/System Pressure - Too Low"},
        {.code = 0x0088, .description = "Fuel Rail/System Pressure - Too High"},
        {.code = 0x0089, .description = "Fuel Pressure Regulator 1 Performance"},
        {.code = 0x0090, .description = "Fuel Pressure Regulator 1 Control Circuit"},
        {.code = 0x0091, .description = "Fuel Pressure Regulator 1 Control Circuit Low"},
        {.code = 0x0092, .description = "Fuel Pressure Regulator 1 Control Circuit High"},
        {.code = 0x0093, .description = "Fuel System Leak Detected - Large Leak"},
        {.code = 0x0094, .description = "Fuel System Leak Detected - Small Leak"},
        {.code = 0x0095, .description = "Intake Air Temperature Sensor 2 Circuit"},
        {.code = 0x0096, .description = "Intake Air Temperature Sensor 2 Circuit Range/Performance"},
        {.code = 0x0097, .description = "Intake Air Temperature Sensor 2 Circuit Low"},
        {.code = 0x0098, .description = "Intake Air Temperature Sensor 2 Circuit High"},
        {.code = 0x0099, .description = "Intake Air Temperature Sensor 2 Circuit Intermittent/Erratic"},
        {.code = 0x0100, .description = "Mass or Volume Air Flow Circuit"},
        {.code = 0x0101, .description = "Mass or Volume Air Flow Circuit Range/Performance"},
        {.code = 0x0102, .description = "Mass or Volume Air Flow Circuit Low Input"},
        {.code = 0x0103, .description = "Mass or Volume Air Flow Circuit High Input"},
        {.code = 0x0104, .description = "Mass or Volume Air Flow Circuit Intermittent"},
        {.code = 0x0105, .description = "Manifold Absolute Pressure/Barometric Pressure Circuit"},
        {.code = 0x0106, .description = "Manifold Absolute Pressure/Barometric Pressure Circuit Range/Performance"},
        {.code = 0x0107, .description = "Manifold Absolute Pressure/Barometric Pressure Circuit Low Input"},
        {.code = 0x0108, .description = "Manifold Absolute Pressure/Barometric Pressure Circuit High Input"},
        {.code = 0x0109, .description = "Manifold Absolute Pressure/Barometric Pressure Circuit Intermittent"},
        {.code = 0x0110, .description = "Intake Air Temperature Sensor 1 Circuit"},
        {.code = 0x0111, .description = "Intake Air Temperature Sensor 1 Circuit Range/Performance"},
        {.code = 0x0112, .description = "Intake Air Temperature Sensor 1 Circuit Low"},
        {.code = 0x0113, .description = "Intake Air Temperature Sensor 1 Circuit High"},
        {.code = 0x0114, .description = "Intake Air Temperature Sensor 1 Circuit Intermittent"},
        {.code = 0x0115, .description = "Engine Coolant Temperature Circuit"},
        {.code = 0x0116, .description = "Engine Coolant Temperature Circuit Range/Performance"},
        {.code = 0x0117, .description = "Engine Coolant Temperature Circuit Low"},
        {.code = 0x0118, .description = "Engine Coolant Temperature Circuit High"},
        {.code = 0x0119, .description = "Engine Coolant Temperature Circuit Intermittent"},
        {.code = 0x0120, .description = "Throttle/Pedal Position Sensor/Switch A Circuit"},
        {.code = 0x0121, .description = "Throttle/Pedal Position Sensor/Switch A Circuit Range/Performance"},
        {.code = 0x0122, .description = "Throttle/Pedal Position Sensor/Switch A Circuit Low"},
        {.code = 0x0123, .description = "Throttle/Pedal Position Sensor/Switch A Circuit High"},
        {.code = 0x0124, .description = "Throttle/Pedal Position Sensor/Switch A Circuit Intermittent"},
        {.code = 0x0125, .description = "Insufficient Coolant Temperature for Closed Loop Fuel Control"},
        {.code = 0x0126, .description = "Insufficient Coolant Temperature for Stable Operation"},
        {.code = 0x0127, .description = "Intake Air Temperature Too High"},
        {.code = 0x0128, .description = "Coolant Thermostat (Coolant Temperature Below)"},
        {.code = 0x0129, .description = "Barometric Pressure Too Low"},
        {.code = 0x0130, .description = "O2 Sensor Circuit"},
        {.code = 0x0131, .description = "O2 Sensor Circuit Low Voltage"},
        {.code = 0x0132, .description = "O2 Sensor Circuit High Voltage"},
        {.code = 0x0133, .description = "O2 Sensor Circuit Slow Response"},
        {.code = 0x0134, .description = "O2 Sensor Circuit No Activity Detected"},
        {.code = 0x0135, .description = "O2 Sensor Heater Circuit"},
        {.code = 0x0136, .description = "O2 Sensor Circuit"},
        {.code = 0x0137, .description = "O2 Sensor Circuit Low Voltage"},
        {.code = 0x0138, .description = "O2 Sensor Circuit High Voltage"},
        {.code = 0x0139, .description = "O2 Sensor Circuit Slow Response"},
        {.code = 0x0140, .description = "O2 Sensor Circuit No Activity Detected"},
        {.code = 0x0141, .description = "O2 Sensor Heater Circuit"},
        {.code = 0x0142, .description = "O2 Sensor Circuit"},
        {.code = 0x0143, .description = "O2 Sensor Circuit Low Voltage"},
        {.code = 0x0144, .description = "O2 Sensor Circuit High Voltage"},
        {.code = 0x0145, .description = "O2 Sensor Circuit Slow Response"},
        {.code = 0x0146, .description = "O2 Sensor Circuit No Activity Detected"},
        {.code = 0x0147, .description = "O2 Sensor Heater Circuit"},
        {.code = 0x0148, .description = "Fuel Delivery Error"},
        {.code = 0x0149, .description = "Fuel Timing Error"},
        {.code = 0x0150, .description = "O2 Sensor Circuit"},
        {.code = 0x0151, .description = "O2 Sensor Circuit Low Voltage"},
        {.code = 0x0152, .description = "O2 Sensor Circuit High Voltage"},
        {.code = 0x0153, .description = "O2 Sensor Circuit Slow Response"},
        {.code = 0x0154, .description = "O2 Sensor Circuit No Activity Detected"},
        {.code = 0x0155, .description = "O2 Sensor Heater Circuit"},
        {.code = 0x0156, .description = "O2 Sensor Circuit"},
        {.code = 0x0157, .description = "O2 Sensor Circuit Low Voltage"},
        {.code = 0x0158, .description = "O2 Sensor Circuit High Voltage"},
        {.code = 0x0159, .description = "O2 Sensor Circuit Slow Response"},
        {.code = 0x0160, .description = "O2 Sensor Circuit No Activity Detected"},
        {.code = 0x0161, .description = "O2 Sensor Heater Circuit"},
        {.code = 0x0162, .description = "O2 Sensor Circuit"},
        {.code = 0x0163, .description = "O2 Sensor Circuit Low Voltage"},
        {.code = 0x0164, .description = "O2 Sensor Circuit High Voltage"},
        {.code = 0x0165, .description = "O2 Sensor Circuit Slow Response"},
        {.code = 0x0166, .description = "O2 Sensor Circuit No Activity Detected"},
        {.code = 0x0167, .description = "O2 Sensor Heater Circuit"},
        {.code = 0x0168, .description = "Fuel Temperature Too High"},
        {.code = 0x0169, .description = "Incorrect Fuel Composition"},
        {.code = 0x0170, .description = "Fuel Trim"},
        {.code = 0x0171, .description = "System Too Lean"},
        {.code = 0x0172, .description = "System Too Rich"},
        {.code = 0x0173, .description = "Fuel Trim"},
        {.code = 0x0174, .description = "System Too Lean"},
        {.code = 0x0175, .description = "System Too Rich"},
        {.code = 0x0176, .description = "Fuel Composition Sensor Circuit"},
        {.code = 0x0177, .description = "Fuel Composition Sensor Circuit Range/Performance"},
        {.code = 0x0178, .description = "Fuel Composition Sensor Circuit Low"},
        {.code = 0x0179, .description = "Fuel Composition Sensor Circuit High"},
        {.code = 0x0180, .description = "Fuel Temperature Sensor A Circuit"},
        {.code = 0x0181, .description = "Fuel Temperature Sensor A Circuit Range/Performance"},
        {.code = 0x0182, .description = "Fuel Temperature Sensor A Circuit Low"},
        {.code = 0x0183, .description = "Fuel Temperature Sensor A Circuit High"},
        {.code = 0x0184, .description = "Fuel Temperature Sensor A Circuit Intermittent"},
        {.code = 0x0185, .description = "Fuel Temperature Sensor B Circuit"},
        {.code = 0x0186, .description = "Fuel Temperature Sensor B Circuit Range/Performance"},
        {.code = 0x0187, .description = "Fuel Temperature Sensor B Circuit Low"},
        {.code = 0x0188, .description = "Fuel Temperature Sensor B Circuit High"},
        {.code = 0x0189, .description = "Fuel Temperature Sensor B Circuit Intermittent"},
        {.code = 0x0190, .description = "Fuel Rail Pressure Sensor Circuit"},
        {.code = 0x0191, .description = "Fuel Rail Pressure Sensor Circuit Range/Performance"},
        {.code = 0x0192, .description = "Fuel Rail Pressure Sensor Circuit Low"},
        {.code = 0x0193, .description = "Fuel Rail Pressure Sensor Circuit High"},
        {.code = 0x0194, .description = "Fuel Rail Pressure Sensor Circuit Intermittent"},
        {.code = 0x0195, .description = "Engine Oil Temperature Sensor"},
        {.code = 0x0196, .description = "Engine Oil Temperature Sensor Range/Performance"},
        {.code = 0x0197, .description = "Engine Oil Temperature Sensor Low"},
        {.code = 0x0198, .description = "Engine Oil Temperature Sensor High"},
        {.code = 0x0199, .description = "Engine Oil Temperature Sensor Intermittent"},
        {.code = 0x0200, .description = "Injector Circuit/Open"},
        {.code = 0x0201, .description = "Injector Circuit/Open - Cylinder 1"},
        {.code = 0x0202, .description = "Injector Circuit/Open - Cylinder 2"},
        {.code = 0x0203, .description = "Injector Circuit/Open - Cylinder 3"},
        {.code = 0x0204, .description = "Injector Circuit/Open - Cylinder 4"},
        {.code = 0x0205, .description = "Injector Circuit/Open - Cylinder 5"},
        {.code = 0x0206, .description = "Injector Circuit/Open - Cylinder 6"},
        {.code = 0x0207, .description = "Injector Circuit/Open - Cylinder 7"},
        {.code = 0x0208, .description = "Injector Circuit/Open - Cylinder 8"},
        {.code = 0x0209, .description = "Injector Circuit/Open - Cylinder 9"},
        {.code = 0x0210, .description = "Injector Circuit/Open - Cylinder 10"},
        {.code = 0x0211, .description = "Injector Circuit/Open - Cylinder 11"},
        {.code = 0x0212, .description = "Injector Circuit/Open - Cylinder 12"},
        {.code = 0x0213, .description = "Cold Start Injector 1"},
        {.code = 0x0214, .description = "Cold Start Injector 2"},
        {.code = 0x0215, .description = "Engine Shutoff Solenoid"},
        {.code = 0x0216, .description = "Injector/Injection Timing Control Circuit"},
        {.code = 0x0217, .description = "Engine Coolant Over Temperature Condition"},
        {.code = 0x0218, .description = "Transmission Fluid Over Temperature Condition"},
        {.code = 0x0219, .description = "Engine Overspeed Condition"},
        {.code = 0x0220, .description = "Throttle/Pedal Position Sensor/Switch B Circuit"},
        {.code = 0x0221, .description = "Throttle/Pedal Position Sensor/Switch B Circuit Range/Performance"},
        {.code = 0x0222, .description = "Throttle/Pedal Position Sensor/Switch B Circuit Low"},
        {.code = 0x0223, .description = "Throttle/Pedal Position Sensor/Switch B Circuit High"},
        {.code = 0x0224, .description = "Throttle/Pedal Position Sensor/Switch B Circuit Intermittent"},
        {.code = 0x0225, .description = "Throttle/Pedal Position Sensor/Switch C Circuit"},
        {.code = 0x0226, .description = "Throttle/Pedal Position Sensor/Switch C Circuit Range/Performance"},
        {.code = 0x0227, .description = "Throttle/Pedal Position Sensor/Switch C Circuit Low"},
        {.code = 0x0228, .description = "Throttle/Pedal Position Sensor/Switch C Circuit High"},
        {.code = 0x0229, .description = "Throttle/Pedal Position Sensor/Switch C Circuit Intermittent"},
        {.code = 0x0230, .description = "Fuel Pump Primary Circuit"},
        {.code = 0x0231, .description = "Fuel Pump Secondary Circuit Low"},
        {.code = 0x0232, .description = "Fuel Pump Secondary Circuit High"},
        {.code = 0x0233, .description = "Fuel Pump Secondary Circuit Intermittent"},
        {.code = 0x0234, .description = "Turbo/Super Charger Overboost Condition"},
        {.code = 0x0235, .description = "Turbo/Super Charger Boost Sensor A Circuit"},
        {.code = 0x0236, .description = "Turbo/Super Charger Boost Sensor A Circuit Range/Performance"},
        {.code = 0x0237, .description = "Turbo/Super Charger Boost Sensor A Circuit Low"},
        {.code = 0x0238, .description = "Turbo/Super Charger Boost Sensor A Circuit High"},
        {.code = 0x0239, .description = "Turbo/Super Charger Boost Sensor B Circuit"},
        {.code = 0x0240, .description = "Turbo/Super Charger Boost Sensor B Circuit Range/Performance"},
        {.code = 0x0241, .description = "Turbo/Super Charger Boost Sensor B Circuit Low"},
        {.code = 0x0242, .description = "Turbo/Super Charger Boost Sensor B Circuit High"},
        {.code = 0x0243, .description = "Turbo/Super Charger Wastegate Solenoid A"},
        {.code = 0x0244, .description = "Turbo/Super Charger Wastegate Solenoid A Range/Performance"},
        {.code = 0x0245, .description = "Turbo/Super Charger Wastegate Solenoid A Low"},
        {.code = 0x0246, .description = "Turbo/Super Charger Wastegate Solenoid A High"},
        {.code = 0x0247, .description = "Turbo/Super Charger Wastegate Solenoid B"},
        {.code = 0x0248, .description = "Turbo/Super Charger Wastegate Solenoid B Range/Performance"},
        {.code = 0x0249, .description = "Turbo/Super Charger Wastegate Solenoid B Low"},
        {.code = 0x0250, .description = "Turbo/Super Charger Wastegate Solenoid B High"},
        {.code = 0x0251, .description = "Injection Pump Fuel Metering Control A (Cam/Rotor/Injector)"},
        {.code = 0x0252, .description = "Injection Pump Fuel Metering Control A Range/Performance (Cam/Rotor/Injector)"},
        {.code = 0x0253, .description = "Injection Pump Fuel Metering Control A Low (Cam/Rotor/Injector)"},
        {.code = 0x0254, .description = "Injection Pump Fuel Metering Control A High (Cam/Rotor/Injector)"},
        {.code = 0x0255, .description = "Injection Pump Fuel Metering Control A Intermittent (Cam/Rotor/Injector)"},
        {.code = 0x0256, .description = "Injection Pump Fuel Metering Control B (Cam/Rotor/Injector)"},
        {.code = 0x0257, .description = "Injection Pump Fuel Metering Control B Range/Performance (Cam/Rotor/Injector)"},
        {.code = 0x0258, .description = "Injection Pump Fuel Metering Control B Low (Cam/Rotor/Injector)"},
        {.code = 0x0259, .description = "Injection Pump Fuel Metering Control B High (Cam/Rotor/Injector)"},
        {.code = 0x0260, .description = "Injection Pump Fuel Metering Control B Intermittent (Cam/Rotor/Injector)"},
        {.code = 0x0261, .description = "Cylinder 1 Injector Circuit Low"},
        {.code = 0x0262, .description = "Cylinder 1 Injector Circuit High"},
        {.code = 0x0263, .description = "Cylinder 1 Contribution/Balance"},
        {.code = 0x0264, .description = "Cylinder 2 Injector Circuit Low"},
        {.code = 0x0265, .description = "Cylinder 2 Injector Circuit High"},
        {.code = 0x0266, .description = "Cylinder 2 Contribution/Balance"},
        {.code = 0x0267, .description = "Cylinder 3 Injector Circuit Low"},
        {.code = 0x0268, .description = "Cylinder 3 Injector Circuit High"},
        {.code = 0x0269, .description = "Cylinder 3 Contribution/Balance"},
        {.code = 0x0270, .description = "Cylinder 4 Injector Circuit Low"},
        {.code = 0x0271, .description = "Cylinder 4 Injector Circuit High"},
        {.code = 0x0272, .description = "Cylinder 4 Contribution/Balance"},
        {.code = 0x0273, .description = "Cylinder 5 Injector Circuit Low"},
        {.code = 0x0274, .description = "Cylinder 5 Injector Circuit High"},
        {.code = 0x0275, .description = "Cylinder 5 Contribution/Balance"},
        {.code = 0x0276, .description = "Cylinder 6 Injector Circuit Low"},
        {.code = 0x0277, .description = "Cylinder 6 Injector Circuit High"},
        {.code = 0x0278, .description = "Cylinder 6 Contribution/Balance"},
        {.code = 0x0279, .description = "Cylinder 7 Injector Circuit Low"},
        {.code = 0x0280, .description = "Cylinder 7 Injector Circuit High"},
        {.code = 0x0281, .description = "Cylinder 7 Contribution/Balance"},
        {.code = 0x0282, .description = "Cylinder 8 Injector Circuit Low"},
        {.code = 0x0283, .description = "Cylinder 8 Injector Circuit High"},
        {.code = 0x0284, .description = "Cylinder 8 Contribution/Balance"},
        {.code = 0x0285, .description = "Cylinder 9 Injector Circuit Low"},
        {.code = 0x0286, .description = "Cylinder 9 Injector Circuit High"},
        {.code = 0x0287, .description = "Cylinder 9 Contribution/Balance"},
        {.code = 0x0288, .description = "Cylinder 10 Injector Circuit Low"},
        {.code = 0x0289, .description = "Cylinder 10 Injector Circuit High"},
        {.code = 0x0290, .description = "Cylinder 10 Contribution/Balance"},
        {.code = 0x0291, .description = "Cylinder 11 Injector Circuit Low"},
        {.code = 0x0292, .description = "Cylinder 11 Injector Circuit High"},
        {.code = 0x0293, .description = "Cylinder 11 Contribution/Balance"},
        {.code = 0x0294, .description = "Cylinder 12 Injector Circuit Low"},
        {.code = 0x0295, .description = "Cylinder 12 Injector Circuit High"},
        {.code = 0x0296, .description = "Cylinder 12 Contribution/Balance"},
        {.code = 0x0297, .description = "Vehicle Overspeed Condition"},
        {.code = 0x0298, .description = "Engine Oil Over Temperature"},
        {.code = 0x0299, .description = "Turbo/Super Charger Underboost"},
        {.code = 0x0300, .description = "Engine Misfire Detected"},
        {.code = 0x0301, .description = "Cylinder 1 Misfire Detected"},
        {.code = 0x0302, .description = "Cylinder 2 Misfire Detected"},
        {.code = 0x0303, .description = "Cylinder 3 Misfire Detected"},
        {.code = 0x0304, .description = "Cylinder 4 Misfire Detected"},
        {.code = 0x0305, .description = "Cylinder 5 Misfire Detected"},
        {.code = 0x0306, .description = "Cylinder 6 Misfire Detected"},
        {.code = 0x0307, .description = "Cylinder 7 Misfire Detected"},
        {.code = 0x0308, .description = "Cylinder 8 Misfire Detected"},
        {.code = 0x0309, .description = "Cylinder 9 Misfire Detected"},
        {.code = 0x0310, .description = "Cylinder 10 Misfire Detected"},
        {.code = 0x0311, .description = "Cylinder 11 Misfire Detected"},
        {.code = 0x0312, .description = "Cylinder 12 Misfire Detected"},
        {.code = 0x0313, .description = "Misfire Detected With Low Fuel Level"},
        {.code = 0x0315, .description = "Crankshaft position (CKP) system variation values are not stored in the PCM memory"},
        {.code = 0x0318, .description = "Rough Road Sensor Circuit"},
        {.code = 0x0320, .description = "Ignition/Distributor Engine Speed Input Circuit Malfunction"},
        {.code = 0x0321, .description = "Ignition/Distributor Engine Speed Input Circuit Range/Performance"},
        {.code = 0x0322, .description = "IC Module 4X Reference Circuit No Frequency"},
        {.code = 0x0323, .description = "Ignition/Distributor Engine Speed Input Circuit Intermittent"},
        {.code = 0x0324, .description = "Knock Sensor (KS) Module Performance"},
        {.code = 0x0325, .description = "PCM Knock Sensor Circuit"},
        {.code = 0x0326, .description = "Knock Sensor Circuit Excessive Spark Retard"},
        {.code = 0x0327, .description = "Knock Sensor Circuit Low Voltage"},
        {.code = 0x0328, .description = "Knock Sensor 1 Circuit High Input (Bank 1 or Single Sensor)"},
        {.code = 0x0329, .description = "Knock Sensor 1 Circuit Intermittent (Bank 1 or Single Sensor)"},
        {.code = 0x0330, .description = "Knock Sensor (KS) Circuit Bank 2"},
        {.code = 0x0331, .description = "Knock Sensor 2 Circuit Range/Performance (Bank 2)"},
        {.code = 0x0332, .description = "Knock Sensor 2 Circuit Low Input (Bank 2)"},
        {.code = 0x0333, .description = "Knock Sensor 2 Circuit High Input (Bank 2)"},
        {.code = 0x0334, .description = "Knock Sensor 2 Circuit Intermittent (Bank 2)"},
        {.code = 0x0335, .description = "CKP Sensor A Circuit Performance"},
        {.code = 0x0336, .description = "Crankshaft Position (CKP) Sensor A Performance"},
        {.code = 0x0337, .description = "Crankshaft Position (CKP) Sensor Circuit Low Duty Cycle"},
        {.code = 0x0338, .description = "Crankshaft Position (CKP) Sensor Circuit High Duty Cycle"},
        {.code = 0x0339, .description = "Crankshaft Position (CKP) Sensor Circuit Intermittent"},
        {.code = 0x0340, .description = "Camshaft Position (CMP) Sensor Circuit"},
        {.code = 0x0341, .description = "Camshaft Position (CMP) Sensor Performance"},
        {.code = 0x0342, .description = "Camshaft Position Sensor Circuit Low Input"},
        {.code = 0x0343, .description = "Camshaft Position Sensor Circuit High Input"},
        {.code = 0x0344, .description = "Camshaft Position Sensor Circuit Intermittent"},
        {.code = 0x0350, .description = "Ignition Coil Primary/Secondary Circuit Malfunction"},
        {.code = 0x0351, .description = "Ignition Coil 1 Control Circuit"},
        {.code = 0x0352, .description = "Ignition Coil 2 Control Circuit"},
        {.code = 0x0353, .description = "Ignition Coil 3 Control Circuit"},
        {.code = 0x0354, .description = "Ignition Coil 4 Control Circuit"},
        {.code = 0x0355, .description = "Ignition Coil 5 Control Circuit"},
        {.code = 0x0356, .description = "Ignition Coil 6 Control Circuit"},
        {.code = 0x0357, .description = "Ignition Coil 7 Control Circuit"},
        {.code = 0x0358, .description = "Ignition Coil 8 Control Circuit"},
        {.code = 0x0359, .description = "Ignition Coil I Primary/Secondary Circuit Malfunction"},
        {.code = 0x0360, .description = "Ignition Coil J Primary/Secondary Circuit Malfunction"},
        {.code = 0x0361, .description = "Ignition Coil K Primary/Secondary Circuit Malfunction"},
        {.code = 0x0362, .description = "Ignition Coil L Primary/Secondary Circuit Malfunction"},
        {.code = 0x0370, .description = "Timing Reference High Resolution Signal A Malfunction"},
        {.code = 0x0371, .description = "IC 24X Reference Circuit Too Many Pulses"},
        {.code = 0x0372, .description = "IC 24X Reference Circuit Missing Pulses"},
        {.code = 0x0373, .description = "Timing Reference High Resolution Signal A Intermittent/Erratic Pulses"},
        {.code = 0x0374, .description = "Timing Reference High Resolution Signal A No Pulses"},
        {.code = 0x0375, .description = "Timing Reference High Resolution Signal B Malfunction"},
        {.code = 0x0376, .description = "Timing Reference High Resolution Signal B Too Many Pulses"},
        {.code = 0x0377, .description = "Timing Reference High Resolution Signal B Too Few Pulses"},
        {.code = 0x0378, .description = "Timing Reference High Resolution Signal B Intermittent/Erratic Pulses"},
        {.code = 0x0379, .description = "Timing Reference High Resolution Signal B No Pulses"},
        {.code = 0x0380, .description = "Glow Plug/Heater Circuit A Malfunction"},
        {.code = 0x0381, .description = "Glow Plug/Heater Indicator Circuit Malfunction"},
        {.code = 0x0382, .description = "Exhaust Gas Recirculation Flow Malfunction"},
        {.code = 0x0385, .description = "Crankshaft Position (CKP) Sensor B Circuit"},
        {.code = 0x0386, .description = "Crankshaft Position (CKP) Sensor B Performance"},
        {.code = 0x0387, .description = "Crankshaft Position Sensor B Circuit Low Input"},
        {.code = 0x0388, .description = "Crankshaft Position Sensor B Circuit High Input"},
        {.code = 0x0389, .description = "Crankshaft Position Sensor B Circuit Intermittent"},
        {.code = 0x0400, .description = "Exhaust Gas Recirculation Flow Malfunction"},
        {.code = 0x0401, .description = "Exhaust Gas Recirculation (EGR) Flow Insufficient"},
        {.code = 0x0402, .description = "Exhaust Gas Recirculation Flow Excessive Detected"},
        {.code = 0x0403, .description = "Exhaust Gas Recirculation (EGR) Solenoid Control Circuit"},
        {.code = 0x0404, .description = "Exhaust Gas Recirculation (EGR) Open Position Performance"},
        {.code = 0x0405, .description = "Exhaust Gas Recirculation (EGR) Position Sensor Circuit Low Voltage"},
        {.code = 0x0406, .description = "Exhaust Gas Recirculation Sensor A Circuit High"},
        {.code = 0x0407, .description = "Exhaust Gas Recirculation Sensor B Circuit Low"},
        {.code = 0x0408, .description = "Exhaust Gas Recirculation Sensor B Circuit High"},
        {.code = 0x0410, .description = "Secondary Air Injection (AIR) System"},
        {.code = 0x0411, .description = "Secondary Air Injection (AIR) System"},
        {.code = 0x0412, .description = "Secondary Air Injection (AIR) Solenoid Relay Control Circuit Bank 1"},
        {.code = 0x0413, .description = "Secondary Air Injection System Switching Valve A Circuit Open"},
        {.code = 0x0414, .description = "Secondary Air Injection System Switching Valve A Circuit Shorted"},
        {.code = 0x0415, .description = "Secondary Air Injection System Switching Valve B Circuit Malfunction"},
        {.code = 0x0416, .description = "Secondary Air Injection System Switching Valve B Circuit Open"},
        {.code = 0x0417, .description = "Secondary Air Injection System Switching Valve B Circuit Shorted"},
        {.code = 0x0418, .description = "Secondary Air Injection (AIR) Pump Relay Control Circuit Bank 1"},
        {.code = 0x0419, .description = "Secondary Air Injection (AIR) Pump Relay Control Circuit Bank 2"},
        {.code = 0x0420, .description = "Catalyst System Low Efficiency"},
        {.code = 0x0421, .description = "Warm Up Catalyst Efficiency Below Threshold (Bank 1)"},
        {.code = 0x0422, .description = "Catalyst System Low Efficiency Bank 1"},
        {.code = 0x0423, .description = "Heated Catalyst Efficiency Below Threshold (Bank 1)"},
        {.code = 0x0424, .description = "Heated Catalyst Temperature Below Threshold (Bank 1)"},
        {.code = 0x0430, .description = "Catalyst System Low Efficiency Bank 2"},
        {.code = 0x0431, .description = "Warm Up Catalyst Efficiency Below Threshold (Bank 2)"},
        {.code = 0x0432, .description = "Catalyst System Low Efficiency Bank 2"},
        {.code = 0x0433, .description = "Heated Catalyst Efficiency Below Threshold (Bank 2)"},
        {.code = 0x0434, .description = "Heated Catalyst Temperature Below Threshold (Bank 2)"},
        {.code = 0x0440, .description = "Evaporative Emission (EVAP) System"},
        {.code = 0x0441, .description = "Evaporative Emission Control System Incorrect Purge Flow"},
        {.code = 0x0442, .description = "Evaporative Emission (EVAP) System Small Leak Detected"},
        {.code = 0x0443, .description = "EVAP Purge Solenoid Valve 1 Control Circuit"},
        {.code = 0x0444, .description = "Evaporative Emission Control System Purge Control Valve Circuit Open"},
        {.code = 0x0445, .description = "Evaporative Emission Control System Purge Control Valve Circuit Shorted"},
        {.code = 0x0446, .description = "EVAP Vent Solenoid Valve Control System"},
        {.code = 0x0447, .description = "Evaporative Emission Control System Vent Control Circuit Open"},
        {.code = 0x0448, .description = "Evaporative Emission Control System Vent Control Circuit Shorted"},
        {.code = 0x0449, .description = "Evaporative Emission (EVAP) Vent Solenoid Control Circuit"},
        {.code = 0x0450, .description = "Fuel Tank Pressure Sensor Circuit"},
        {.code = 0x0451, .description = "Evaporative Emission Control System Pressure Sensor Range/Performance"},
        {.code = 0x0452, .description = "Fuel Tank Pressure Sensor Circuit Low Voltage"},
        {.code = 0x0453, .description = "Fuel Tank Pressure Sensor Circuit High Voltage"},
        {.code = 0x0454, .description = "Evaporative Emission Control System Pressure Sensor Intermittent"},
        {.code = 0x0455, .description = "Evaporative Emission (EVAP) System Leak Detected"},
        {.code = 0x0460, .description = "Fuel Level Sensor Circuit"},
        {.code = 0x0461, .description = "Fuel Level Sensor Performance"},
        {.code = 0x0462, .description = "Fuel Level Sensor Circuit Low Voltage"},
        {.code = 0x0463, .description = "Fuel Level Sensor Circuit High Voltage"},
        {.code = 0x0464, .description = "Fuel Level Sensor Circuit Intermittent"},
        {.code = 0x0465, .description = "Purge Flow Sensor Circuit Malfunction"},
        {.code = 0x0466, .description = "Purge Flow Sensor Circuit Range/Performance"},
        {.code = 0x0467, .description = "Purge Flow Sensor Circuit Low Input"},
        {.code = 0x0468, .description = "Purge Flow Sensor Circuit High Input"},
        {.code = 0x0469, .description = "Purge Flow Sensor Circuit Intermittent"},
        {.code = 0x0470, .description = "Exhaust Pressure Sensor Malfunction"},
        {.code = 0x0471, .description = "Exhaust Pressure Sensor Range/Performance"},
        {.code = 0x0472, .description = "Exhaust Pressure Sensor Low"},
        {.code = 0x0473, .description = "Exhaust Pressure Sensor High"},
        {.code = 0x0474, .description = "Exhaust Pressure Sensor Intermittent"},
        {.code = 0x0475, .description = "Exhaust Pressure Control Valve Malfunction"},
        {.code = 0x0476, .description = "Exhaust Pressure Control Valve Range/Performance"},
        {.code = 0x0477, .description = "Exhaust Pressure Control Valve Low"},
        {.code = 0x0478, .description = "Exhaust Pressure Control Valve High"},
        {.code = 0x0479, .description = "Exhaust Pressure Control Valve Intermittent"},
        {.code = 0x0480, .description = "Cooling Fan Relay 1 Control Circuit"},
        {.code = 0x0481, .description = "Cooling Fan Relay 2 Control Circuit"},
        {.code = 0x0482, .description = "Cooling Fan 3 Control Circuit Malfunction"},
        {.code = 0x0483, .description = "Cooling Fan Rationality Check Malfunction"},
        {.code = 0x0484, .description = "Cooling Fan Circuit Over Current"},
        {.code = 0x0485, .description = "Cooling Fan Power/Ground Circuit Malfunction"},
        {.code = 0x0496, .description = "Evaporative Emission (EVAP) System Flow During Non-Purge"},
        {.code = 0x0500, .description = "Vehicle Speed Sensor (VSS) Circuit"},
        {.code = 0x0501, .description = "Vehicle Speed Sensor Range/Performance"},
        {.code = 0x0502, .description = "Vehicle Speed Sensor (VSS) Circuit Low Input"},
        {.code = 0x0503, .description = "Vehicle Speed Sensor (VSS) Circuit Intermittent"},
        {.code = 0x0505, .description = "Idle Control System Malfunction"},
        {.code = 0x0506, .description = "Idle Speed Low"},
        {.code = 0x0507, .description = "Idle Speed High"},
        {.code = 0x0510, .description = "Closed Throttle Position Switch Malfunction"},
        {.code = 0x0512, .description = "Start Switch Circuit"},
        {.code = 0x0520, .description = "Engine Oil Pressure Sensor/Switch Circuit Malfunction"},
        {.code = 0x0521, .description = "Engine Oil Pressure Sensor/Switch Circuit Range/Performance"},
        {.code = 0x0522, .description = "Engine Oil Pressure Sensor/Switch Circuit Low Voltage"},
        {.code = 0x0523, .description = "Engine Oil Pressure Sensor/Switch Circuit High Voltage"},
        {.code = 0x0526, .description = "Cooling Fan Speed Sensor Circuit"},
        {.code = 0x0530, .description = "A/C Refrigerant Pressure Sensor Circuit Malfunction"},
        {.code = 0x0531, .description = "A/C Refrigerant Pressure Sensor Circuit Range/Performance"},
        {.code = 0x0532, .description = "Air Conditioning (A/C) Refrigerant Pressure Sensor Circuit Low Voltage"},
        {.code = 0x0533, .description = "Air Conditioning (A/C) Refrigerant Pressure Sensor Circuit High Voltage"},
        {.code = 0x0534, .description = "Air Conditioner Refrigerant Charge Loss"},
        {.code = 0x0550, .description = "Power Steering Pressure (PSP) Switch Circuit"},
        {.code = 0x0551, .description = "Power Steering Pressure Sensor Circuit Range/Performance"},
        {.code = 0x0552, .description = "Power Steering Pressure Sensor Circuit Low Input"},
        {.code = 0x0553, .description = "Power Steering Pressure Sensor Circuit High Input"},
        {.code = 0x0554, .description = "Power Steering Pressure Sensor Circuit Intermittent"},
        {.code = 0x0560, .description = "System Voltage"},
        {.code = 0x0561, .description = "System Voltage Unstable"},
        {.code = 0x0562, .description = "System Voltage Low (TCM)"},
        {.code = 0x0563, .description = "System Voltage High (TCM)"},
        {.code = 0x0564, .description = "Cruise Control Multi-Function Switch Circuit (PCM)"},
        {.code = 0x0565, .description = "Cruise Control On Signal Malfunction"},
        {.code = 0x0566, .description = "Cruise Control Off Signal Malfunction"},
        {.code = 0x0567, .description = "Cruise Control Resume Signal Malfunction"},
        {.code = 0x0568, .description = "Cruise Control Set Signal Malfunction"},
        {.code = 0x0569, .description = "Cruise Control Coast Signal Malfunction"},
        {.code = 0x0570, .description = "Cruise Control Accel Signal Malfunction"},
        {.code = 0x0571, .description = "Cruise Control Brake Switch Circuit"},
        {.code = 0x0573, .description = "Cruise Control/Brake Switch A Circuit High"},
        {.code = 0x0574, .description = "Vehicle Speed Too High - above 110 mph - Cruise Control Disabled"},
        {.code = 0x0575, .description = "Cruise Control Related Malfunction"},
        {.code = 0x0576, .description = "Cruise Control Related Malfunction"},
        {.code = 0x0576, .description = "Cruise Control Related Malfunction"},
        {.code = 0x0578, .description = "Cruise Control Related Malfunction"},
        {.code = 0x0579, .description = "Cruise Control Related Malfunction"},
        {.code = 0x0580, .description = "Cruise Control Related Malfunction"},
        {.code = 0x0600, .description = "Serial Communication Link Malfunction"},
        {.code = 0x0601, .description = "Control Module Read Only Memory (ROM)"},
        {.code = 0x0602, .description = "Control Module Not Programmed"},
        {.code = 0x0603, .description = "Control Module Long Term Memory Reset"},
        {.code = 0x0604, .description = "Control Module Random Access Memory (RAM)"},
        {.code = 0x0605, .description = "Control Module Programming Read Only Memory (ROM)"},
        {.code = 0x0606, .description = "Control Module Internal Performance"},
        {.code = 0x0607, .description = "ECU Malfunction"},
        {.code = 0x0608, .description = "Control Module VSS Output A Malfunction"},
        {.code = 0x0609, .description = "Control Module VSS Output B Malfunction"},
        {.code = 0x0610, .description = "Control Module Vehicle Options Incorrect"},
        {.code = 0x0615, .description = "Starter Relay Control Circuit"},
        {.code = 0x0616, .description = "Starter Relay Control Circuit Low Voltage"},
        {.code = 0x0617, .description = "Starter Relay Control Circuit High Voltage"},
        {.code = 0x0620, .description = "Generator Control Circuit Malfunction"},
        {.code = 0x0621, .description = "Generator L-Terminal Circuit"},
        {.code = 0x0622, .description = "Generator F-Terminal Circuit"},
        {.code = 0x0625, .description = "Generator F-Terminal Circuit Low Voltage"},
        {.code = 0x0626, .description = "Generator F-Terminal Circuit High Voltage"},
        {.code = 0x0628, .description = "Fuel Pump Relay Control Circuit Low Voltage"},
        {.code = 0x0629, .description = "Fuel Pump Relay Control Circuit High Voltage"},
        {.code = 0x0638, .description = "Throttle Actuator Control (TAC) Command Performance"},
        {.code = 0x0641, .description = "PCM voltage out of tolerance condition on the 5-volt reference circuit"},
        {.code = 0x0645, .description = "Air Conditioning (A/C) Clutch Relay Control Circuit"},
        {.code = 0x0646, .description = "Air Conditioning (A/C) Clutch Relay Control Circuit"},
        {.code = 0x0647, .description = "Air Conditioning (A/C) Clutch Relay Control Circuit"},
        {.code = 0x0650, .description = "Malfunction Indicator Lamp (MIL) Control Circuit"},
        {.code = 0x0651, .description = "PCM voltage out of tolerance condition on the 5-volt reference circuit"},
        {.code = 0x0654, .description = "Engine RPM Output Circuit Malfunction"},
        {.code = 0x0655, .description = "Engine Hot Lamp Output Control Circuit Malfunction"},
        {.code = 0x0656, .description = "Fuel Level Output Circuit Malfunction"},
        {.code = 0x0660, .description = "Intake Manifold Tuning (IMT) Valve Solenoid Control Circuit"},
        {.code = 0x0661, .description = "Intake Manifold Tuning (IMT) Valve Solenoid Control Circuit Low Voltage"},
        {.code = 0x0662, .description = "Intake Manifold Tuning (IMT) Valve Solenoid Control Circuit High Voltage"},
        {.code = 0x0685, .description = "Engine Controls Ignition Relay Control Circuit (PCM)"},
        {.code = 0x0691, .description = "Cooling Fan Relay Control Circuit Low Voltage"},
        {.code = 0x0693, .description = "Cooling Fan Relay Control Circuit Low Voltage"},
        {.code = 0x0692, .description = "Cooling Fan Relay Control Circuit High Voltage"},
        {.code = 0x0694, .description = "Cooling Fan Relay Control Circuit High Voltage"},
        {.code = 0x0700, .description = "Transmission Control System Malfunction"},
        {.code = 0x0701, .description = "Transmission Control System Range/Performance"},
        {.code = 0x0702, .description = "Transmission Control System Electrical"},
        {.code = 0x0703, .description = "Brake Switch Circuit Malfunction"},
        {.code = 0x0704, .description = "Clutch Switch Input Circuit Malfunction"},
        {.code = 0x0705, .description = "Trans Range Switch Circuit"},
        {.code = 0x0706, .description = "Trans Range Switch Performance"},
        {.code = 0x0707, .description = "Transmission Range Sensor Circuit Low Input"},
        {.code = 0x0708, .description = "Transmission Range Sensor Circuit High Input"},
        {.code = 0x0709, .description = "Transmission Range Sensor Circuit Intermittent"},
        {.code = 0x0710, .description = "Transmission Fluid Temperature Sensor Circuit Malfunction"},
        {.code = 0x0711, .description = "TFT Sensor Circuit Range/Performance"},
        {.code = 0x0712, .description = "Transmission Fluid Temperature (TFT) Sensor Circuit Low Input"},
        {.code = 0x0713, .description = "Transmission Fluid Temperature (TFT) Sensor Circuit High Input"},
        {.code = 0x0714, .description = "Transmission Fluid Temperature Sensor Circuit Intermittent"},
        {.code = 0x0715, .description = "Input/Turbine Speed Sensor Circuit Malfunction"},
        {.code = 0x0716, .description = "Input Speed Sensor Circuit Intermittent"},
        {.code = 0x0717, .description = "Input Speed Sensor Circuit Low Input"},
        {.code = 0x0718, .description = "Input/Turbine Speed Sensor Circuit Intermittent"},
        {.code = 0x0719, .description = "Brake Switch Circuit Low Input"},
        {.code = 0x0720, .description = "Output Speed Sensor Circuit Malfunction"},
        {.code = 0x0721, .description = "Output Speed Sensor Range/Performance"},
        {.code = 0x0722, .description = "Output Speed Sensor Circuit Low Input"},
        {.code = 0x0723, .description = "Output Speed Sensor Intermittent"},
        {.code = 0x0724, .description = "Brake Switch Circuit High Input"},
        {.code = 0x0725, .description = "Engine Speed Input Circuit"},
        {.code = 0x0726, .description = "Engine Speed Input Circuit Range/Performance"},
        {.code = 0x0727, .description = "Engine Speed Circuit No Signal"},
        {.code = 0x0728, .description = "Engine Speed Input Circuit Intermittent"},
        {.code = 0x0730, .description = "Incorrect Gear Ratio"},
        {.code = 0x0731, .description = "Incorrect 1st Gear Ratio"},
        {.code = 0x0732, .description = "Incorrect 2nd Gear Ratio"},
        {.code = 0x0733, .description = "Incorrect 3rd Gear Ratio"},
        {.code = 0x0734, .description = "Incorrect 4th Gear Ratio"},
        {.code = 0x0735, .description = "Gear 5 Incorrect ratio"},
        {.code = 0x0736, .description = "Reverse incorrect gear ratio"},
        {.code = 0x0740, .description = "TCC Enable Solenoid Circuit Electrical"},
        {.code = 0x0741, .description = "TCC System Stuck Off"},
        {.code = 0x0742, .description = "TCC System Stuck On"},
        {.code = 0x0743, .description = "TCC Enable Solenoid Circuit Electrical"},
        {.code = 0x0744, .description = "Torque Converter Clutch Circuit Intermittent"},
        {.code = 0x0745, .description = "Pressure Control Solenoid Malfunction"},
        {.code = 0x0746, .description = "Pressure Control Solenoid Performance or Stuck Off"},
        {.code = 0x0747, .description = "Pressure Control Solenoid Stuck On"},
        {.code = 0x0748, .description = "Pressure Control Solenoid Circuit Electrical"},
        {.code = 0x0749, .description = "Pressure Control Solenoid Intermittent"},
        {.code = 0x0750, .description = "Shift Solenoid A Malfunction"},
        {.code = 0x0751, .description = "1-2 Shift Solenoid Valve Performance - No First or Fourth Gear"},
        {.code = 0x0752, .description = "1-2 Shift Solenoid Valve Performance - No Second or Third Gear"},
        {.code = 0x0753, .description = "1-2 Shift Solenoid Circuit Electrical"},
        {.code = 0x0754, .description = "Shift Solenoid A Intermittent"},
        {.code = 0x0755, .description = "Shift Solenoid B Malfunction"},
        {.code = 0x0756, .description = "2-3 Shift Solenoid Valve Performance - No First or Second Gear"},
        {.code = 0x0757, .description = "2-3 Shift Solenoid Valve Performance - No Third or Fourth Gear"},
        {.code = 0x0758, .description = "2-3 Shift Solenoid Circuit Electrical"},
        {.code = 0x0759, .description = "Shift Solenoid B Intermittent"},
        {.code = 0x0760, .description = "Shift Solenoid C Malfunction"},
        {.code = 0x0761, .description = "Shift Solenoid C Performance or Stuck Off"},
        {.code = 0x0762, .description = "Shift Solenoid C Stuck On"},
        {.code = 0x0763, .description = "Shift Solenoid C Electrical"},
        {.code = 0x0764, .description = "Shift Solenoid C Intermittent"},
        {.code = 0x0765, .description = "Shift Solenoid D Malfunction"},
        {.code = 0x0766, .description = "Shift Solenoid D Performance or Stuck Off"},
        {.code = 0x0767, .description = "Shift Solenoid D Stuck On"},
        {.code = 0x0768, .description = "Shift Solenoid D Electrical"},
        {.code = 0x0769, .description = "Shift Solenoid D Intermittent"},
        {.code = 0x0770, .description = "Shift Solenoid E Malfunction"},
        {.code = 0x0771, .description = "Shift Solenoid E Performance or Stuck Off"},
        {.code = 0x0772, .description = "Shift Solenoid E Stuck On"},
        {.code = 0x0773, .description = "Shift Solenoid E Electrical"},
        {.code = 0x0774, .description = "Shift Solenoid E Intermittent"},
        {.code = 0x0780, .description = "Shift Malfunction"},
        {.code = 0x0781, .description = "1-2 Shift Malfunction"},
        {.code = 0x0782, .description = "2-3 Shift Malfunction"},
        {.code = 0x0783, .description = "3-4 Shift Malfunction"},
        {.code = 0x0784, .description = "4-5 Shift Malfunction"},
        {.code = 0x0785, .description = "3-2 Shift Solenoid Circuit Electrical"},
        {.code = 0x0786, .description = "Shift/Timing Solenoid Range/Performance"},
        {.code = 0x0787, .description = "Shift/Timing Solenoid Low"},
        {.code = 0x0788, .description = "Shift/Timing Solenoid High"},
        {.code = 0x0789, .description = "Shift/Timing Solenoid Intermittent"},
        {.code = 0x0790, .description = "Normal/Performance Switch Circuit Malfunction"},
        {.code = 0x0801, .description = "Reverse Inhibit Control Circuit Malfunction"},
        {.code = 0x0803, .description = "1-4 Upshift (Skip Shift) Solenoid Control Circuit Malfunction"},
        {.code = 0x0804, .description = "1-4 Upshift (Skip Shift) Lamp Control Circuit Malfunction"},
        {.code = 0x0850, .description = "Park/Neutral Position (PNP) Switch Circuit"},
        {.code = 0x0856, .description = "Powertrain Indicated Traction Control Malfunction"},
        {.code = 0x0894, .description = "Transmission Component Slipping"},
        {.code = 0x0897, .description = "PCM detects a calculated transmission fluid life of 10 percent or less"},
        {.code = 0x0962, .description = "Line Pressure Control (PC) Solenoid Control Circuit Low Voltage (TCM)"},
        {.code = 0x0963, .description = "Line Pressure Control (PC) Solenoid Control Circuit High Voltage (TCM)"},
        {.code = 0x0966, .description = "Clutch Pressure Control (PC) Solenoid Control Circuit Low Voltage (TCM)"},
        {.code = 0x0967, .description = "Clutch Pressure Control (PC) Solenoid Control Circuit High Voltage (TCM)"},
        {.code = 0x0970, .description = "Shift Pressure control (PC) Solenoid Control Circuit Low Voltage (TCM)"},
        {.code = 0x0971, .description = "Shift Pressure Control (PC) Solenoid Control High Voltage (TCM)"},
        {.code = 0x0973, .description = "PCM detects an open or short to ground in the 1-2 SS valve circuit"},
        {.code = 0x0974, .description = "PCM detects a continuous short to voltage in the 1-2 SS valve circuit"},
        {.code = 0x0976, .description = "PCM detects a continuous open or short to ground in the 2-3 SS valve circuit"},
        {.code = 0x0977, .description = "PCM detects a continuous short to voltage in the 2-3 SS valve circuit"},
        {.code = 0x0979, .description = "Shift Solenoid (SS) 3 Control Circuit Low Voltage (TCM)"},
        {.code = 0x0980, .description = "Shift Solenoid (SS) 3 Control Circuit High Voltage (TCM)"},
        {.code = 0x0982, .description = "Shift Solenoid (SS) 4 Control Circuit High Voltage (TCM)"},
        {.code = 0x0983, .description = "Shift Solenoid (SS) 4 Control Circuit High Voltage (TCM)"},
        {.code = 0x0985, .description = "Shift Solenoid (SS) 5 Control Circuit Low Voltage (TCM)"},
        {.code = 0x0986, .description = "Shift Solenoid (SS) 5 Control Circuit High Voltage (TCM)"},
};